name: Issue Reply

on: 
  issues:
    types: [opened,labeled,edited]
  label:
    types: [created]
  workflow_dispatch:
  
env:
  REPO_NAME: ${{ github.event.repository.name }}
  GH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
  
jobs:
  reply-helper:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.pullIssuesPorter.outputs.IMAGE_NAME }}
      SUCCESS: ${{ steps.successCheck.outputs.SUCCESS }}
    steps:
      - name: check-issue
        id: check_issue_id
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          title-includes: 'gcr.io,k8s.gcr.io,ghcr.io'
      - name: image
        if: steps.check_issue_id.outputs.check-result == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome PR。

            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎PR。
          
