name: Issue Reply

on: 
  issues:
    types: [opened,labeled,edited]
  label:
    types: [created]
  workflow_dispatch:

jobs:
  reply-helper:
    runs-on: ubuntu-latest
    steps:
      - name: check-issue
        id: check_issue_id
        if: github.event.label.name == 'image' 
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'check-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          title-includes: 'gcr.io,k8s.gcr.io,ghcr.io'
      - name: image
        if: steps.check_issue_id.outputs.check-result == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome PR。

            你好 @${{ github.event.issue.user.login }}，我们完全同意你的提议/反馈，欢迎PR。
          
