# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_IMAGEVERSE }}
      - 
        name: Docker pull and push
#         run: |
#           docker pull ghcr.io/cross-rs/aarch64-linux-android:main  
#           docker tag  ghcr.io/cross-rs/aarch64-linux-android:main  smallverse/ghcr.io_cross-rs_aarch64-linux-android:main       
#           docker push smallverse/ghcr.io_cross-rs_aarch64-linux-android:main
#           echo "------ push image end"
#           docker pull ghcr.io/cross-rs/arm-linux-androideabi:main
#           docker tag ghcr.io/cross-rs/arm-linux-androideabi:main smallverse/ghcr.io_cross-rs_arm-linux-androideabi:main
#           docker push smallverse/ghcr.io_cross-rs_arm-linux-androideabi:main
#           echo "------ push image end"
#           docker pull ghcr.io/cross-rs/armv7-linux-androideabi:main
#           docker tag ghcr.io/cross-rs/armv7-linux-androideabi:main smallverse/ghcr.io_cross-rs_armv7-linux-androideabi:main
#           docker push smallverse/ghcr.io_cross-rs_armv7-linux-androideabi:main
#           echo "------ push image end"
#           docker pull ghcr.io/cross-rs/x86_64-pc-windows-gnu:main
#           docker tag ghcr.io/cross-rs/x86_64-pc-windows-gnu:main smallverse/ghcr.io_cross-rs_x86_64-pc-windows-gnu:main
#           docker push smallverse/ghcr.io_cross-rs_x86_64-pc-windows-gnu:main
#           echo "------ push image end"
        run: |
            echo "------ test "
